spring:
  application:
    name: tasklist
    version: 1.0.0-SNAPSHOT
  profiles:
    active: ${PROFILE:dev}
  datasource:
    driverClassName: org.postgresql.Driver
    url: 
      jdbc:postgresql://${DS_URL:localhost}:${DS_PORT:5433}/${DS_DATABASE:sansys_database}
    password: ${DS_PASS:postgres}
    username: ${DS_USER:postgres}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: 'true'
    hibernate:
      ddl-auto: update
    generate-ddl: 'true'
management:
  endpoints:
    web:
      exposure:
        include: '*'
server:
  port: ${PORT:8080}
  forward-headers-strategy: framework
logging:
  level:
    root: info
    org.springframework.web: info
    br.com.jtech.tasklist: debug
  file:
    name: ./logs/${spring.application.name}.log
springdoc:
  api-docs:
    groups:
      enabled: 'true'
    path: /doc/tasklist/v3/api-documents
  swagger-ui:
    enabled: 'true'
    path: /doc/tasklist/v1/api.html
api:
  version: v1
  description: Description here
  url:
    homologation: http://${HOMOLOGATION_SERVER:172.30.1.24}:${HOMOLOGATION_PORT:8081}
    production: ${PRODUCTION_URI:http://${spring.application.name}.jtech.com.br}
